proposition de compléments pour la mise en cohérence modèle de données / schéma de données
etalab/guides.etalab.gouv.fr pull request #205
Opened 2023-02-15 23:20 UTC by loco-philippe

Voici quelques compléments aux modifications réalisées par Pierlou (pas de modifications importantes)

2023-02-16 09:15 UTC, Pierlou requested changes

2023-02-16 09:15 UTC, Pierlou commented on qualite/3-documenter-les-donnees.md
> +
Commentaire général : les modèles de données ne sont actuellement pas un prérequis à la publication, mais bien une part de la documentation d'un jeu de données. Par ailleurs, peu de jeux de données sont assez complexes pour nécessiter un modèle, c'est plutôt au niveau de croisements de plusieurs jeux de données que cela pourrait être utile mais rien n'est implémenté dans ce sens à l'heure actuelle. Nous mettons en avant la démarche des schémas car elle nous semble plus pertinente relativement à la majorité des données publiées sur data.gouv

2023-02-16 10:18 UTC, loco-philippe commented on producteurs-schemas/2-phase-concertation.md
> +- les relations de dépendance entre deux champs
Oui, c'est vrai -> à supprimer

2023-02-16 14:18 UTC, loco-philippe reviewed
J'ai pris en compte les demandes (justifiées) au travers de commits mais je ne sais pas si je peux les lier à cette Pull Request. Est-ce que j'en recrée une autre ?

2023-02-16 14:26 UTC, loco-philippe commented
Finalement les commits effectués semblent bien intégrés à la Pull Request -> tout va bien !

2023-02-23 16:22 UTC, Pierlou requested changes

2023-02-23 16:22 UTC, Pierlou commented on qualite/3-documenter-les-donnees.md
> +Une fois le modèle établi, il convient de définir le découpage en fichiers. On peut décider de regrouper des entités dans un même fichier ou au contraire d'associer une seule entité à un fichier.
"ou au contraire d'associer une seule entité à un fichier" => "ou au contraire de créer un fichier par entité" ?
NB : le choix de découper ou de regrouper les entités n'est pas neutre : découper les entités en plusieurs fichiers permet de gagner de la place (ce qui peut ne pas être un problème si les tailles en jeu sont raisonnables) mais demande aux réutilisateurs de savoir faire des fusions de tables par la suite, ce qui peut être un frein à l'ouverture des données. Nous encourageons plutôt le regroupement des entités, pour gagner en ergonomie au détriment de la taille des fichiers.

2023-03-01 11:22 UTC, Pierlou approved these changes

2023-03-02 10:33 UTC, Pierlou commented
Bonjour Philippe, j'ai corrigé un problème de versoning qui empêchait le déploiement normal dans les tests (qui sont nécessaires pour merge sur master). Il faut maintenant que tu rebase ta branche avec la branche master pour bénéficier de ces changements et permettre aux tests de passer. Ensuite on pourra merge cette branche sur master.

2023-03-02 13:22 UTC, loco-philippe commented
Bonjour Pierlou,

Merci de ton retour, je m'en occupe cet après-midi et je te préviens dès
que le commit avec la branche actualisée est fait.

Bonne après-midi

On Thu, Mar 2, 2023 at 11:33 AM Pierlou Ramade ***@***.***>
wrote:

> Bonjour Philippe, j'ai corrigé un problème de versoning qui empêchait le
> déploiement normal dans les tests (qui sont nécessaires pour merge sur
> master). Il faut maintenant que tu rebase ta branche avec la branche master
> pour bénéficier de ces changements et permettre aux tests de passer.
> Ensuite on pourra merge cette branche sur master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/etalab/guides.etalab.gouv.fr/pull/205#issuecomment-1451647764>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWAONLQWUSLKYFVR25CNGNLW2BZPPANCNFSM6AAAAAAU5OSLWE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-03-02 13:58 UTC, loco-philippe commented
J'ai eu le malheur de renommer ma branche avant la clôture de la PR, ce qui a conduit à la suppression de la branche et à la clôture de la PR. Après restauration de la branche et réouverture de la PR, ça a l'air OK.

2023-03-02 13:59 UTC, merged